"""
TwinBrain — Real-time Brain Visualization Server
=================================================

WebSocket server for real-time communication with the web frontend.

Supported request types (``type`` field):
  get_state        – Return current demo brain activity (200-region float array)
  simulate         – Virtual stimulation simulation (WC / surrogate MLP / GNN)
  load_cache       – Load a .pt cache file and stream its full time series
  list_cache_files – List all discoverable .pt cache files on the server
  infer_ec         – Infer effective connectivity (Jacobian or perturbation method)
  validate_ec      – Validate EC reliability (half-split, distance, FC comparison)
  analyze_brain    – Label-free brain state analysis (deviation map / hub metrics)

Start the server::

    server = BrainVisualizationServer(model_path="model.pt", host="127.0.0.1")
    asyncio.run(server.start_async())
"""

import asyncio
import json
import logging
from typing import Dict, Any, Set, Optional
from pathlib import Path
from datetime import datetime

# Try to import websockets, but make it optional
try:
    import websockets
    WEBSOCKETS_AVAILABLE = True
except ImportError:
    WEBSOCKETS_AVAILABLE = False
    logging.warning("websockets package not available. Install with: pip install websockets")

# Import ModelServer
try:
    from .model_server import ModelServer
    MODEL_SERVER_AVAILABLE = True
except ImportError:
    MODEL_SERVER_AVAILABLE = False
    logging.warning("ModelServer not available")


def _import_brain_state_analyzer():
    """Robustly import BrainStateAnalyzer regardless of the import context."""
    # 1. Package-relative import (normal usage)
    try:
        from .brain_state_analyzer import BrainStateAnalyzer as _BSA
        return _BSA
    except (ImportError, SystemError):
        pass
    # 2. Absolute package import (when the package root is on sys.path)
    try:
        from unity_integration.brain_state_analyzer import BrainStateAnalyzer as _BSA
        return _BSA
    except ImportError:
        pass
    # 3. Direct file import via importlib (standalone / test scripts)
    try:
        import importlib.util
        _spec = importlib.util.spec_from_file_location(
            "brain_state_analyzer",
            str(Path(__file__).parent / "brain_state_analyzer.py"),
        )
        _mod = importlib.util.module_from_spec(_spec)
        _spec.loader.exec_module(_mod)
        return _mod.BrainStateAnalyzer
    except Exception:
        return None


def _make_fibonacci_brain_positions(n: int = 200) -> "np.ndarray":
    """Compute and return the (n, 3) Fibonacci-sphere brain region coordinates.

    Reproduces the *exact* positions generated by ``makeBrainPositions()`` in
    ``web_frontend/app.js``, so that any distance-based computation on the
    server (Gaussian spatial spread, EC vs anatomical distance) uses the same
    coordinate frame as the 3-D visualisation.

    This function always performs the computation.  Caching is the
    responsibility of the caller — use ``_get_brain_positions`` to obtain a
    cached copy and avoid redundant trigonometric work.

    Args:
        n: total number of regions (must be even; default 200).

    Returns:
        Newly allocated Float32 array of shape (n, 3):
        columns are [x (L-R), y (I-S), z (P-A)].
    """
    import numpy as _np

    half  = n // 2
    daz   = 2 * _np.pi * (2 - (1 + _np.sqrt(5)) / 2)  # golden angle ≈ 2.40 rad

    # Vectorized over `half` regions per hemisphere (replaces inner Python loop).
    i_arr  = _np.arange(half, dtype=_np.float64)
    t_arr  = (i_arr + 0.5) / half            # (half,) elevation parameter ∈ (0, 1)
    el_arr = 1.0 - 1.85 * t_arr              # (half,) elevation component
    r_arr  = _np.sqrt(_np.maximum(0.0, 1.0 - el_arr ** 2))  # (half,) radial
    az_arr = daz * i_arr                     # (half,) azimuth
    lat    = _np.abs(r_arr * _np.cos(az_arr)) * 0.85 + 0.15  # (half,) lateral extent
    bulge  = 9 * _np.exp(-((el_arr + 0.22) ** 2) * 5)        # (half,) temporal lobe bulge

    pos = _np.empty((n, 3), dtype=_np.float32)
    for h, sign in enumerate((-1, 1)):
        start = h * half
        pos[start: start + half, 0] = sign * (lat * 55 + bulge + 9)
        pos[start: start + half, 1] = el_arr * 63 - 4
        pos[start: start + half, 2] = r_arr * _np.sin(az_arr) * 76 - 8
    return pos


# Module-level cache so the positions are computed only once per process.
_BRAIN_POSITIONS_CACHE: "Optional[np.ndarray]" = None

# Maximum recursion depth for _find_all_hetero_data to guard against
# corrupted / unexpectedly deep data structures.
_MAX_HETERO_RECURSION_DEPTH: int = 100


def _get_brain_positions(n: int = 200) -> "np.ndarray":
    """Return the module-level cached Fibonacci brain positions.

    On the first call (or if ``n`` changes) the positions are computed via
    ``_make_fibonacci_brain_positions`` and stored in ``_BRAIN_POSITIONS_CACHE``.
    Subsequent calls with the same ``n`` return the cached array directly,
    avoiding 200 trigonometric operations per simulation request.

    Note: the cache holds a single array.  Passing a different ``n`` invalidates
    the cache and triggers a recomputation.
    """
    global _BRAIN_POSITIONS_CACHE
    if _BRAIN_POSITIONS_CACHE is None or _BRAIN_POSITIONS_CACHE.shape[0] != n:
        _BRAIN_POSITIONS_CACHE = _make_fibonacci_brain_positions(n)
    return _BRAIN_POSITIONS_CACHE


class BrainVisualizationServer:
    """WebSocket server for real-time brain visualization.

    Endpoints: get_state, simulate, load_cache, list_cache_files,
               infer_ec, validate_ec, analyze_brain.
    """

    # Directories searched for .pt cache files (in priority order).
    # "test_file3" and "Unity_TwinBrain" are project-specific subdirectory names
    # commonly used in TwinBrain experiment layouts.
    _CACHE_SEARCH_DIRS = [Path("."), Path("graph_cache"), Path("test_file3"), Path("Unity_TwinBrain"), Path("..")]
    # Well-known cache filenames that take priority over arbitrary .pt files.
    _PREFERRED_CACHE_NAMES = ["hetero_graphs.pt", "eeg_data.pt"]
    # Minimum file size (bytes) to be considered a valid cache (filters out
    # empty placeholder files and zero-byte torch.save() artefacts).
    _MIN_CACHE_SIZE = 1024

    def __init__(
        self,
        model_path: Optional[str] = None,
        output_dir: Optional[str] = None,
        host: str = "0.0.0.0",
        port: int = 8765,
        # Legacy params kept for backward-compat; no longer used
        model=None, exporter=None, simulator=None,
    ):
        if not WEBSOCKETS_AVAILABLE:
            raise ImportError("websockets package is required. Install with: pip install websockets")

        self.host = host
        self.port = port
        self.logger = logging.getLogger(__name__)

        if model is not None or exporter is not None or simulator is not None:
            self.logger.warning(
                "BrainVisualizationServer: 'model', 'exporter', and 'simulator' "
                "parameters are deprecated and will be ignored. "
                "Use 'model_path' to load a trained model."
            )

        self.model_server = None
        if MODEL_SERVER_AVAILABLE and model_path:
            self.model_server = ModelServer(
                model_path=model_path,
                output_dir=output_dir or "unity_project/brain_data/model_output"
            )
            self.logger.info("✓ ModelServer initialized")

        self.clients: Set = set()

        # Cache for trained PerturbationAnalyzer instances.
        # Key: (cache_file_path_str, n_lags) so the surrogate is only retrained
        # when the source data or lag window changes, not on every infer_ec call.
        self._ec_analyzer_cache: dict = {}

        # Last loaded time series — stored so handle_validate_ec and
        # handle_analyze_brain can access it without re-loading the .pt file.
        self._loaded_time_series: Optional["np.ndarray"] = None  # (T, 200)
        self._loaded_cache_path:  Optional[str]          = None
        # Raw (un-per-frame-normalized) time series for deviation analysis.
        # EEG per-frame normalization loses temporal structure, making z-score
        # deviation maps near-zero.  The raw series preserves real task differences.
        self._loaded_raw_time_series: Optional["np.ndarray"] = None  # (T, 200)
    
    async def register_client(self, websocket):
        """Register a new client connection."""
        self.clients.add(websocket)
        self.logger.info(f"Client connected: {websocket.remote_address}")
        
        # Send welcome message
        welcome = {
            "type": "welcome",
            "message": "Connected to TwinBrain server",
            "version": "1.0"
        }
        await websocket.send(json.dumps(welcome))
    
    async def unregister_client(self, websocket):
        """Unregister a client connection."""
        self.clients.discard(websocket)
        self.logger.info(f"Client disconnected: {websocket.remote_address}")

    async def handle_client(self, websocket, path=None):
        """Handle client connection and requests."""
        await self.register_client(websocket)

        try:
            async for message in websocket:
                try:
                    request = json.loads(message)
                    response = await self.process_request(request)
                    await websocket.send(json.dumps(response))
                except json.JSONDecodeError:
                    error = {"type": "error", "message": "Invalid JSON"}
                    await websocket.send(json.dumps(error))
                except Exception as e:
                    self.logger.error(f"Error processing request: {e}")
                    error = {"type": "error", "message": str(e)}
                    await websocket.send(json.dumps(error))
        finally:
            await self.unregister_client(websocket)

    async def process_request(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Process client request and return response."""
        request_type = request.get("type", "unknown")

        # Accept legacy/alternative naming conventions
        if request_type == "get_brain_state":
            request_type = "get_state"
        elif request_type == "simulate_stimulation":
            request_type = "simulate"

        self.logger.info(f"Processing request: {request_type}")

        try:
            if request_type == "get_state":
                return await self.handle_get_state(request)
            elif request_type == "simulate":
                return await self.handle_simulate(request)
            elif request_type == "load_cache":
                return await self.handle_load_cache(request)
            elif request_type == "list_cache_files":
                return await self.handle_list_cache_files(request)
            elif request_type == "infer_ec":
                return await self.handle_infer_ec(request)
            elif request_type == "validate_ec":
                return await self.handle_validate_ec(request)
            elif request_type == "analyze_brain":
                return await self.handle_analyze_brain(request)
            else:
                self.logger.warning(f"Unknown request type: {request_type}")
                return {
                    "type": "error",
                    "success": False,
                    "message": f"Unknown request type: {request_type}"
                }
        except Exception as e:
            self.logger.error(f"Error processing {request_type}: {e}", exc_info=True)
            return {
                "type": "error",
                "success": False,
                "message": f"Server error: {str(e)}"
            }
    async def handle_get_state(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Return current brain state with flat activity array.

        Uses a 7-network (Schaefer) oscillation model for demo mode so that
        different brain networks show distinct, correlated dynamics rather than
        pure white noise.
        """
        import numpy as np
        import time

        n_regions  = 200
        t          = time.time()

        # Schaefer 7-network approximate frequency/phase profile
        # Visual, Somatomotor, DorsAttn, VentAttn, Limbic, FrontPar, Default
        net_freqs  = np.array([0.012, 0.020, 0.035, 0.028, 0.008, 0.025, 0.010])
        net_phases = np.array([0.0,   1.0,   2.1,   0.7,   3.2,   1.8,   0.4  ])
        net_size   = n_regions // 7

        rng = np.random.default_rng(int(t * 200) % 65536)

        # Vectorized over all 200 regions simultaneously.
        # net_idx[i] = network assignment for region i (0-indexed, capped at 6)
        i_arr    = np.arange(n_regions)
        net_idx  = np.minimum(i_arr // net_size, 6)
        v = (0.36
             + 0.22 * np.sin(2 * np.pi * net_freqs[net_idx] * t
                              + net_phases[net_idx] + i_arr * 0.08)
             + 0.04 * np.sin(2 * np.pi * 0.005 * t + i_arr * 0.25)
             + rng.normal(0, 0.025, n_regions))
        activity = np.clip(v, 0.0, 1.0).tolist()

        return {
            "type":     "brain_state",
            "activity": activity,       # flat [0,1] array, length = n_regions
            "success":  True,
        }

    async def handle_simulate(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Handle stimulation simulation request.

        Accepts both formats:
          - Flat:   {type, target_regions, amplitude, pattern, frequency, duration}
          - Nested: {type, stimulation: {target_regions, amplitude, ...}}
        """
        # Accept both nested (legacy) and flat (web frontend) parameter layouts
        if "stimulation" in request and isinstance(request["stimulation"], dict):
            stimulation = request["stimulation"]
        else:
            stimulation = request  # flat format sent by web frontend
        
        try:
            import torch
            import numpy as np

            def _compute_top_affected(frames, cf_frames, peak_idx, target_ids, top_k=15):
                """Return top affected non-target regions and the per-region delta array.

                Compares stimulated vs counterfactual frames at ``peak_idx`` to find
                the regions that changed most due to stimulation.  Target regions are
                excluded so the list highlights PROPAGATION to other areas.

                Returns:
                    top_affected : list of {"region_id": int, "delta": float} dicts,
                                   sorted by |delta| descending, length ≤ top_k
                    peak_delta   : list of 200 floats (stim − CF at peak_idx)
                """
                safe_peak = min(peak_idx, len(frames) - 1, len(cf_frames) - 1)
                if not frames or not cf_frames or safe_peak < 0:
                    return [], []
                stim_act = np.array(frames[safe_peak]["activity"], dtype=np.float32)
                cf_act   = np.array(cf_frames[safe_peak]["activity"], dtype=np.float32)
                delta    = stim_act - cf_act
                target_set = set(target_ids)
                # Exclude target regions — we want to highlight PROPAGATION effects
                candidates = [i for i in range(len(delta)) if i not in target_set]
                candidates_sorted = sorted(candidates, key=lambda i: -abs(delta[i]))
                top_affected = [
                    {"region_id": int(i), "delta": float(delta[i])}
                    for i in candidates_sorted[:top_k]
                ]
                return top_affected, delta.tolist()

            # Parse stimulation parameters
            target_regions = stimulation.get("target_regions", [])
            amplitude = stimulation.get("amplitude", 0.5)
            pattern = stimulation.get("pattern", "sine")
            frequency = stimulation.get("frequency", 10.0)
            duration = stimulation.get("duration", 20)
            # The frontend sends the currently-displayed frame's activity so the
            # stimulation starts from the user's actual selected brain state.
            initial_state = stimulation.get("initial_state", None)
            
            # Validate target regions
            if not isinstance(target_regions, list) or len(target_regions) == 0:
                return {
                    "type": "error",
                    "success": False,
                    "message": "target_regions must be a non-empty list"
                }
            
            # Validate and clamp values
            amplitude = float(max(0.0, min(10.0, amplitude)))
            frequency = float(max(0.1, min(100.0, frequency)))
            duration = int(max(1, min(1000, duration)))
            
            # Filter valid region IDs
            n_regions = 200
            valid_regions = [r for r in target_regions if isinstance(r, int) and 0 <= r < n_regions]
            
            if len(valid_regions) == 0:
                return {
                    "type": "error",
                    "success": False,
                    "message": f"No valid target regions (must be 0-{n_regions-1})"
                }
            
            if len(valid_regions) < len(target_regions):
                self.logger.warning(f"Filtered {len(target_regions) - len(valid_regions)} invalid region IDs")
                target_regions = valid_regions
            
            # Use ModelServer if available
            if self.model_server:
                # Create timestamped output directory only when ModelServer will actually
                # use it — avoids leaving empty dirs on every demo/surrogate simulation.
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                output_base = Path(self.model_server.output_dir)
                stim_output_dir = output_base / "stimulation" / f"stim_{timestamp}"
                stim_output_dir.mkdir(parents=True, exist_ok=True)
                self.logger.info(f"Stimulation output directory: {stim_output_dir}")
                self.logger.info(f"Using ModelServer for stimulation simulation")
                # Convert the user's initial_state list to a tensor so ModelServer
                # starts from the actual brain state rather than random noise.
                init_tensor = None
                if initial_state is not None:
                    arr = np.array(initial_state[:n_regions], dtype=np.float32)
                    init_tensor = torch.tensor(arr).unsqueeze(-1)  # (n_regions, 1)
                responses = self.model_server.simulate_stimulation(
                    target_regions=target_regions,
                    amplitude=amplitude,
                    pattern=pattern,
                    frequency=frequency,
                    duration=duration,
                    initial_state=init_tensor,
                    subject_id="stimulation"
                )
                
                # Auto-save each frame as JSON for progressive playback support.
                self.logger.info(f"Auto-saving {len(responses)} stimulation frames to {stim_output_dir}")
                for idx, response in enumerate(responses):
                    json_path = stim_output_dir / f"frame_{idx:04d}.json"
                    with open(json_path, 'w', encoding='utf-8') as f:
                        json.dump(response, f, indent=2)

                # Create sequence index
                index_data = {
                    "type": "stimulation_sequence",
                    "timestamp": timestamp,
                    "stimulation_params": {
                        "target_regions": target_regions,
                        "amplitude": amplitude,
                        "pattern": pattern,
                        "frequency": frequency,
                        "duration": duration
                    },
                    "n_frames": len(responses),
                    "output_dir": str(stim_output_dir),
                    "files": [f"frame_{i:04d}.json" for i in range(len(responses))]
                }
                index_path = stim_output_dir / "sequence_index.json"
                with open(index_path, 'w', encoding='utf-8') as f:
                    json.dump(index_data, f, indent=2)
                
                self.logger.info(f"✓ Stimulation results auto-saved to: {stim_output_dir}")
                
                frames = [{"activity": self._extract_activity_array(r)} for r in responses]
                # Counterfactual: run ModelServer with amplitude=0 so frame count and
                # dynamics exactly match the stimulated run (valid scientific comparison).
                # Using _demo_simulate here gave a different frame count (PRE+DUR+POST vs
                # DUR) and different dynamics, making the CF toggle misleading.
                cf_responses = self.model_server.simulate_stimulation(
                    target_regions=target_regions,
                    amplitude=0.0,
                    pattern=pattern,
                    frequency=frequency,
                    duration=duration,
                    initial_state=init_tensor,
                    subject_id="stimulation_cf",
                )
                cf_frames = [{"activity": self._extract_activity_array(r)} for r in cf_responses]
                # Pattern-aware start_frame: point to the frame with maximum stim effect.
                # ModelServer has no pre-stim frames (frame 0 = first stim step), so we
                # index directly without adding a PRE offset.
                _PULSE_PEAK_K = 9
                _ms_dur = min(int(duration), 60)
                if pattern == "pulse":
                    _ms_peak_k = min(_PULSE_PEAK_K, _ms_dur - 1)
                elif pattern == "ramp":
                    _ms_peak_k = max(0, _ms_dur * 3 // 4)
                else:  # sine, constant
                    _ms_peak_k = _ms_dur // 2
                ms_top_affected, ms_peak_delta = _compute_top_affected(
                    frames, cf_frames, _ms_peak_k, valid_regions
                )
                return {
                    "type": "simulation_result",
                    "success": True,
                    "n_frames": len(frames),
                    "frames": frames,
                    "counterfactual_frames": cf_frames,
                    "modality": "simulation",
                    "method": "model_server",
                    "start_frame": _ms_peak_k,
                    "top_affected": ms_top_affected,
                    "peak_delta": ms_peak_delta,
                    "saved_to": str(stim_output_dir),
                    "index_file": str(index_path),
                }

            # ── Data-driven surrogate path (requires prior EC inference) ──────
            # If the user has already run "推断有效连接", a trained MLP surrogate is
            # available in _ec_analyzer_cache.  Use predict_trajectory to produce a
            # REAL data-driven forecast instead of generic Wilson-Cowan dynamics.
            #
            # Stimulation mechanics (NPI principle):
            #   Only the exact target regions receive the external perturbation.
            #   stim_weights is a point / indicator function (1.0 at targets, 0
            #   elsewhere), NOT a spatial Gaussian.  This ensures that every
            #   change seen in OTHER regions comes exclusively from what the
            #   surrogate learned about functional connectivity — the model
            #   handles all propagation.  Using a Gaussian spread here would
            #   pre-distribute the stimulation to neighbours before the model
            #   runs, mixing the physical-spread assumption with the learned
            #   connectivity and making the two impossible to disentangle.
            surrogate_frames = None
            if initial_state is not None and self._ec_analyzer_cache:
                analyzer = list(self._ec_analyzer_cache.values())[-1]
                if (analyzer._surrogate is not None
                        and analyzer._ts_mean is not None
                        and analyzer.n_regions == n_regions):
                    try:
                        # Point stimulation: 1.0 at each selected target, 0 elsewhere.
                        # The surrogate MLP propagates the effect to connected regions.
                        sw = np.zeros(n_regions, dtype=np.float32)
                        for tid in target_regions:
                            if 0 <= tid < n_regions:
                                sw[tid] = 1.0

                        PRE_s  = 10
                        DUR_s  = min(int(duration), 60)
                        POST_s = 10

                        def _stim_amp_s(k: int) -> float:
                            # (k+0.5)/DUR_s: centers each frame in its time slot so
                            # the bell envelope is never evaluated at exactly 0 or 1,
                            # ensuring non-zero amplitude even when DUR_s == 1 or 2.
                            progress = (k + 0.5) / max(DUR_s, 1)
                            if pattern == "sine":
                                slow_c = min(frequency / 10.0, 3.0)
                                return amplitude * (np.sin(np.pi * progress)
                                                    + 0.20 * np.sin(2 * np.pi * slow_c * progress))
                            elif pattern == "pulse":
                                return amplitude * np.exp(-k * 0.12)
                            elif pattern == "ramp":
                                return amplitude * progress
                            else:
                                return amplitude * min(1.0, k / max(DUR_s * 0.15, 1.0))

                        # Unified stim_fn covers all three phases:
                        #   k < PRE_s            → pre-stim (surrogate runs, no external input)
                        #   PRE_s ≤ k < PRE_s+DUR_s → stimulation active
                        #   k ≥ PRE_s+DUR_s      → post-stim recovery (no external input)
                        # Using a single call with n_warmup=0 (lag window warms up during
                        # the pre-stim region where stim_fn returns 0), so the pre-stim
                        # frames show genuine baseline dynamics, not static copies.
                        def _stim_fn_full(k: int) -> float:
                            if k < PRE_s:
                                return 0.0
                            stim_k = k - PRE_s
                            if stim_k < DUR_s:
                                return _stim_amp_s(stim_k)
                            return 0.0

                        init_arr = np.array(initial_state[:n_regions], dtype=np.float32)

                        surrogate_frames = analyzer.predict_trajectory(
                            initial_state=init_arr,
                            stim_weights=sw,
                            stim_fn=_stim_fn_full,
                            n_steps=PRE_s + DUR_s + POST_s,
                        )

                        # Counterfactual: same initial state, zero stimulation.
                        # Because predict_trajectory is deterministic (no noise), the
                        # pre-stim frames will be identical between stimulated and
                        # counterfactual; they diverge from frame PRE_s onwards.
                        surrogate_cf = analyzer.predict_trajectory(
                            initial_state=init_arr,
                            stim_weights=sw,
                            stim_fn=lambda k: 0.0,
                            n_steps=PRE_s + DUR_s + POST_s,
                        )
                        self.logger.info(
                            f"使用已训练代理模型预测刺激轨迹 ({len(surrogate_frames)} 帧)"
                        )
                    except Exception as _exc:
                        self.logger.warning(
                            f"代理预测失败，回退到 Wilson-Cowan: {_exc}"
                        )
                        surrogate_frames = None
                        surrogate_cf = None

            if surrogate_frames is not None:
                # Same pattern-aware peak logic as the WC path: start at the frame
                # where stimulation effect is most visible, not at stim onset (k=0).
                # PRE_s and DUR_s are already set above (line ~586/587).
                _PULSE_PEAK_K = 9  # empirical: pulse decay, effect peaks near k=9
                if pattern == "pulse":
                    _s_peak_k = min(_PULSE_PEAK_K, DUR_s - 1)
                elif pattern == "ramp":
                    _s_peak_k = max(0, DUR_s * 3 // 4)
                else:
                    _s_peak_k = DUR_s // 2
                _s_peak_idx = PRE_s + _s_peak_k
                s_top_affected, s_peak_delta = _compute_top_affected(
                    surrogate_frames, surrogate_cf, _s_peak_idx, valid_regions
                )
                return {
                    "type": "simulation_result",
                    "success": True,
                    "n_frames": len(surrogate_frames),
                    "frames": surrogate_frames,
                    "counterfactual_frames": surrogate_cf,
                    "modality": "simulation",
                    "method": "surrogate_mlp",
                    "start_frame": _s_peak_idx,
                    "top_affected": s_top_affected,
                    "peak_delta": s_peak_delta,
                }

            # Final fallback: Wilson-Cowan recurrent dynamics (no trained model needed).
            # Generate stimulated trajectory, then null (amplitude=0) counterfactual.
            # Both calls re-seed rng=np.random.default_rng(0) so noise is identical,
            # making the comparison between stim and null scientifically clean.
            #
            # When the frontend provides no initial_state (no data loaded), each
            # _demo_simulate call would independently call time.time(), giving slightly
            # different t0 values and therefore slightly different baselines.  Pre-generate
            # one deterministic baseline here so both runs start from the same state.
            if initial_state is None:
                _fallback = self._generate_demo_time_series(T=1)
                initial_state = _fallback[0].tolist()
            frames = self._demo_simulate(
                target_regions=target_regions,
                amplitude=amplitude,
                pattern=pattern,
                frequency=frequency,
                duration=duration,
                n_regions=n_regions,
                initial_state=initial_state,
            )
            # Counterfactual: same dynamics but with amplitude=0
            cf_frames = self._demo_simulate(
                target_regions=target_regions,
                amplitude=0.0,
                pattern=pattern,
                frequency=frequency,
                duration=duration,
                n_regions=n_regions,
                initial_state=initial_state,
            )
            # Compute pattern-aware peak frame so the browser starts playback at
            # the frame with the MOST VISIBLE stimulation effect, not at the boring
            # first stim frame where the sine bell is barely non-zero.
            # Numerical audit (see AGENTS.md) showed start_frame=10 (stim onset)
            # yields only 0.001 visible change — 193× less than the peak frame.
            # NOTE: _WC_PRE and _WC_MAX_DUR are kept separate from PRE_s/DUR_s
            # because PRE_s/DUR_s are only defined when the surrogate path is
            # entered (i.e., when _ec_analyzer_cache is non-empty).  The WC
            # fallback can be reached without entering the surrogate path, so
            # we define these independently using the same values as
            # _demo_simulate's PRE=10 and _MAX_STIM_FRAMES=60.
            _WC_PRE      = 10   # must match _demo_simulate's PRE
            _WC_MAX_DUR  = 60   # must match _demo_simulate's _MAX_STIM_FRAMES
            _PULSE_PEAK_K = 9   # empirical: pulse decay, accumulated effect peaks near k=9
            _wc_dur = min(int(duration), _WC_MAX_DUR)
            if pattern == "pulse":
                # Pulse decays from k=0; accumulated deviation peaks at k ≈ 9
                _peak_k = min(_PULSE_PEAK_K, _wc_dur - 1)
            elif pattern == "ramp":
                # Ramp grows continuously; deviation is maximum near the last stim frame
                _peak_k = max(0, _wc_dur * 3 // 4)
            else:
                # sine and constant: bell/plateau centre gives maximum effect
                _peak_k = _wc_dur // 2
            _wc_peak_idx = _WC_PRE + _peak_k
            top_affected, peak_delta = _compute_top_affected(
                frames, cf_frames, _wc_peak_idx, valid_regions
            )
            return {
                "type": "simulation_result",
                "success": True,
                "n_frames": len(frames),
                "frames": frames,
                "counterfactual_frames": cf_frames,
                "modality": "simulation",
                "method": "wilson_cowan",
                "start_frame": _wc_peak_idx,
                "top_affected": top_affected,
                "peak_delta": peak_delta,
            }
                
        except Exception as e:
            self.logger.error(f"Error in simulation: {e}")
            return {
                "type": "error",
                "message": f"Simulation failed: {str(e)}"
            }
    
    # ------------------------------------------------------------------ #
    #  Perturbation-based Effective Connectivity inference                 #
    # ------------------------------------------------------------------ #

    async def handle_infer_ec(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Infer effective connectivity using NPI-inspired perturbation analysis.

        Request fields:
          method  (str, optional): "jacobian" (default) | "perturbation" | "demo"
          n_lags  (int, optional): lag window for surrogate model (default 5)
          path    (str, optional): .pt cache file to extract time series from;
                                   if omitted uses the last loaded cache or demo data.

        Response:
          {type: "ec_result",
           method: str,
           ec_flat: [200*200 floats],     -- row-major EC matrix
           top_sources: [int*10],         -- most influential source regions
           top_targets: [int*10],         -- most receptive target regions
           activity_delta: [200 floats],  -- predicted activity change from top 3 sources
           fit_quality: {train_mse, val_mse, overfit_ratio, reliable, n_epochs},
           success: true}
        """
        import numpy as np

        method = request.get("method", "jacobian")
        n_lags = int(request.get("n_lags", 5))

        try:
            # Try relative import first (normal package usage); fall back to
            # absolute import when the module is loaded as a standalone script
            # in test environments where the parent package stub may not support
            # relative imports.
            try:
                from .perturbation_analyzer import PerturbationAnalyzer
            except (ImportError, SystemError):
                from unity_integration.perturbation_analyzer import PerturbationAnalyzer
        except ImportError:
            return {"type": "error", "message": "PerturbationAnalyzer 模块未找到"}

        # ── Demo mode (no data needed) ─────────────────────────────────────
        if method == "demo":
            analyzer = PerturbationAnalyzer(n_regions=200, n_lags=n_lags)
            ec = analyzer.infer_ec_demo()
            result = analyzer.ec_to_dict(ec)
            top_src = result["top_sources"]
            result["activity_delta"] = analyzer.predict_activity_delta(
                top_src[:3], amplitude=0.5, ec_matrix=ec
            ).tolist()
            result["method"]  = "demo"
            result["success"] = True
            result["type"]    = "ec_result"
            self.logger.info("EC 推断完成 (演示模式)")
            return result

        # ── Data-driven modes: need time series ────────────────────────────
        raw_path   = request.get("path")
        cache_path = Path(raw_path) if raw_path else (
            Path(self._loaded_cache_path) if self._loaded_cache_path
            else self._find_cache_file()
        )

        time_series = None

        # Priority 1: reuse the time series already loaded into the session
        # (set by handle_load_cache when the user picked a file from the dropdown).
        # Prefer raw values: for fMRI, global percentile normalization already
        # preserves temporal dynamics; for EEG, per-frame min-max normalization
        # loses the temporal amplitude envelope (the surrogate MLP would see a
        # flat, featureless signal), so the original µV values are essential for
        # meaningful EC inference.  This matches standard EEG/fMRI preprocessing
        # practice (per-channel z-score prior to Granger/DCM analysis).
        if not raw_path and self._loaded_time_series is not None:
            ts_src = self._loaded_raw_time_series or self._loaded_time_series
            if len(ts_src) >= n_lags + 10:
                time_series = ts_src
                self.logger.info(
                    f"EC 推断: 使用已加载时序 {time_series.shape} "
                    f"(raw={'yes' if self._loaded_raw_time_series is not None else 'no'})"
                )

        # Priority 2: load from the specified (or auto-detected) cache file.
        if time_series is None and cache_path and cache_path.exists():
            try:
                import torch
                # weights_only=False is required because cache files contain
                # HeteroData objects (torch_geometric custom classes) that
                # cannot be deserialized with weights_only=True.
                # Mitigated by only loading files from the local project tree.
                data_pt = torch.load(str(cache_path), map_location="cpu",
                                     weights_only=False)
                both = self._extract_time_series_both(data_pt)
                # Prefer fMRI, fall back to EEG.  Use raw values so that EEG
                # temporal dynamics are preserved (per-frame activity is useless
                # for the surrogate MLP — see note above).
                primary_frames = both.get("fmri") or both.get("eeg") or []
                if primary_frames:
                    time_series = np.array(
                        [f.get("raw", f.get("activity", [0.5] * 200)) for f in primary_frames],
                        dtype=np.float32,
                    )  # (T, 200)
                    self.logger.info(
                        f"EC 推断: 从缓存加载 {time_series.shape[0]} 帧 × 200 区域 (raw)"
                    )
            except Exception as exc:
                self.logger.warning(f"缓存加载失败，使用演示数据: {exc}")

        if time_series is None or len(time_series) < n_lags + 10:
            self.logger.info("EC 推断: 生成合成振荡时序数据（演示用）")
            time_series = self._generate_demo_time_series(300)
            cache_path = None   # no file backing; don't cache by path

        # ── Reuse cached surrogate when possible ───────────────────────────
        cache_key = (str(cache_path) if cache_path else "__synthetic__", n_lags)
        analyzer  = self._ec_analyzer_cache.get(cache_key)
        need_train = analyzer is None

        if need_train:
            analyzer = PerturbationAnalyzer(n_regions=200, n_lags=n_lags)
            self.logger.info(f"训练 MLP 代理模型: {time_series.shape} …")
            analyzer.fit_surrogate(
                time_series,
                n_lags=n_lags,
                # num_epochs is a ceiling; early stopping (patience=12) will
                # terminate training before this limit when validation MSE
                # stops improving, so a higher cap costs nothing in practice
                # and gives the model more time to converge on larger datasets.
                num_epochs=80,
                batch_size=64,
                lr=1e-3,
            )
            # Cache the trained analyzer so subsequent infer_ec requests (e.g.
            # switching method jacobian→perturbation) skip retraining.
            self._ec_analyzer_cache[cache_key] = analyzer
        else:
            self.logger.info("EC 推断: 复用已缓存代理模型（跳过训练）")

        # ── Infer EC ───────────────────────────────────────────────────────
        # infer_ec_jacobian samples a random subset of training inputs on every
        # call (np.random.choice without a fixed seed).  Repeated calls on the
        # same data therefore produce slightly different EC matrices.  This is
        # intentional: it trades single-run reproducibility for robustness
        # testing — if top-source rankings remain stable despite the random
        # subset, that is stronger evidence than a single fixed-seed result.
        # Users who need exact reproducibility should use the perturbation
        # method instead, which is fully deterministic for fixed inputs.
        if method == "perturbation":
            ec = analyzer.infer_ec_perturbation(pert_strength=0.05)
        else:
            ec = analyzer.infer_ec_jacobian(
                n_samples=min(100, len(time_series) - n_lags)
            )

        result = analyzer.ec_to_dict(ec)
        top_src = result["top_sources"]
        # Use top-3 sources for a more representative activity spread prediction
        result["activity_delta"] = analyzer.predict_activity_delta(
            top_src[:3], amplitude=0.5, ec_matrix=ec
        ).tolist()
        result["method"]  = method
        result["success"] = True
        result["type"]    = "ec_result"
        self.logger.info(
            f"EC 推断完成 ({method}), 影响力最强区域: {top_src[:5]}, "
            f"可靠: {result.get('fit_quality', {}).get('reliable', 'N/A')}"
        )
        return result

    # ------------------------------------------------------------------ #
    #  EC Validation                                                        #
    # ------------------------------------------------------------------ #

    async def handle_validate_ec(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Validate EC reliability using three complementary checks.

        Checks (all use the EXISTING trained surrogate — no retraining):
          half_split  – EC consistency between first-half vs second-half of
                        training samples (higher Pearson r = more reliable)
          distance    – |EC[i,j]| vs anatomical distance correlation
                        (expected negative: nearby regions interact more strongly)
          fc_compare  – Pearson r between |EC| and FC (correlation matrix);
                        high similarity means EC is redundant with simpler FC.
                        Well-calibrated EC should add information beyond FC.

        Request: { type: "validate_ec" }
        Response: { type: "ec_validation_result", success: True, results: {...} }
        """
        import numpy as np

        BrainStateAnalyzer = _import_brain_state_analyzer()
        if BrainStateAnalyzer is None:
            return {"type": "error", "message": "BrainStateAnalyzer 模块未找到"}

        # Require a trained EC analyzer
        if not self._ec_analyzer_cache:
            return {
                "type": "error",
                "success": False,
                "message": "尚未推断 EC，请先点击「推断有效连接」",
            }

        analyzer = list(self._ec_analyzer_cache.values())[-1]
        if analyzer._surrogate is None or analyzer._input_X is None:
            return {
                "type": "error",
                "success": False,
                "message": "代理模型未训练，请先推断 EC",
            }

        results = {}

        # ── 1. Half-split reliability ──────────────────────────────────────
        try:
            r_hs, detail_hs = BrainStateAnalyzer.ec_half_split_reliability(
                surrogate=analyzer._surrogate,
                input_X=analyzer._input_X,
                n_regions=analyzer.n_regions,
            )
            results["half_split"] = detail_hs
        except Exception as exc:
            results["half_split"] = {"error": str(exc)}

        # ── 2. EC vs anatomical distance ───────────────────────────────────
        if analyzer._last_ec is not None:
            try:
                dist_result = BrainStateAnalyzer.ec_vs_distance_correlation(
                    ec_matrix=analyzer._last_ec,
                )
                results["distance"] = dist_result
            except Exception as exc:
                results["distance"] = {"error": str(exc)}

        # ── 3. EC vs FC (functional connectivity from training data) ───────
        if analyzer._last_ec is not None and self._loaded_time_series is not None:
            try:
                ts = self._loaded_time_series          # (T, 200)
                # Pearson FC (correlation between time courses of all region pairs)
                fc = np.corrcoef(ts.T)                 # (200, 200)
                np.fill_diagonal(fc, 0.0)
                ec_abs = np.abs(analyzer._last_ec)
                np.fill_diagonal(ec_abs, 0.0)
                f_ec = ec_abs.flatten()
                f_fc = np.abs(fc.flatten())
                r_ef = float(np.corrcoef(f_ec, f_fc)[0, 1]) if f_ec.std() > 0 else 0.0
                interp = (
                    "EC ≈ FC（因果关系与相关性高度重叠，EC 的额外信息有限）" if r_ef > 0.7
                    else ("EC 与 FC 中度相关（因果关系略超过单纯相关）" if r_ef > 0.4
                    else "EC 与 FC 差异明显（EC 提供了超出相关分析的因果信息）")
                )
                results["fc_vs_ec"] = {
                    "ec_fc_pearson_r": round(r_ef, 3),
                    "interpretation":  interp,
                }
            except Exception as exc:
                results["fc_vs_ec"] = {"error": str(exc)}

        self.logger.info(f"EC 验证完成: {list(results.keys())}")
        return {
            "type":    "ec_validation_result",
            "success": True,
            "results": results,
        }

    # ------------------------------------------------------------------ #
    #  Brain State Analysis (label-free)                                   #
    # ------------------------------------------------------------------ #

    async def handle_analyze_brain(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Label-free brain state analysis: deviation map or graph metrics.

        Methods:
          deviation     – split loaded time series into two halves, compute
                          per-region z-score deviation map (early vs late window)
          graph_metrics – compute EC-based hub scores and overlay on 3D brain

        Request: { type: "analyze_brain",
                   method: "deviation" | "graph_metrics",
                   window1_start: int, window1_end: int,  (optional)
                   window2_start: int, window2_end: int   (optional)
                 }
        Response: { type: "brain_analysis_result",
                    method: str,
                    activity: [200 floats],   # overlay for 3D view
                    summary: {…},
                    regions_of_interest: [int],
                    success: true
                  }
        """
        import numpy as np

        BrainStateAnalyzer = _import_brain_state_analyzer()
        if BrainStateAnalyzer is None:
            return {"type": "error", "message": "BrainStateAnalyzer 模块未找到"}

        method = request.get("method", "deviation")

        # ── graph_metrics: requires EC matrix ─────────────────────────────
        if method == "graph_metrics":
            if not self._ec_analyzer_cache:
                return {
                    "type": "error",
                    "success": False,
                    "message": "请先推断有效连接（EC），再使用图论分析",
                }
            analyzer = list(self._ec_analyzer_cache.values())[-1]
            if analyzer._last_ec is None:
                return {
                    "type": "error",
                    "success": False,
                    "message": "EC 矩阵不可用，请先推断有效连接",
                }
            try:
                metrics = BrainStateAnalyzer.compute_graph_metrics(analyzer._last_ec)
                hub_scores = np.array(metrics["hub_scores"], dtype=np.float32)
                hs_max = hub_scores.max()
                overlay = (hub_scores / hs_max).tolist() if hs_max > 0 else hub_scores.tolist()
                return {
                    "type":    "brain_analysis_result",
                    "method":  "graph_metrics",
                    "activity": overlay,
                    "summary": {
                        "global_efficiency": metrics["global_eff"],
                        "density":           metrics["density"],
                        "top_hubs":          metrics["top_hubs"],
                        "interpretation":    (
                            f"全脑效率 {metrics['global_eff']:.3f}，"
                            f"连接密度 {metrics['density']:.3f}。"
                            f"最强枢纽区域（Hub）: {[r+1 for r in metrics['top_hubs'][:5]]}"
                        ),
                    },
                    "regions_of_interest": metrics["top_hubs"][:10],
                    "success": True,
                }
            except Exception as exc:
                return {"type": "error", "message": f"图论分析失败: {exc}"}

        # ── deviation: requires loaded time series ─────────────────────────
        if self._loaded_time_series is None:
            return {
                "type": "error",
                "success": False,
                "message": "请先加载 .pt 文件，再使用偏差分析",
            }

        # Prefer raw (un-normalised) time series so that per-frame-normalised EEG
        # data retains genuine between-task amplitude differences.  Fall back to
        # the normalised series if no raw data was stored (e.g. fMRI global-norm).
        ts = (
            self._loaded_raw_time_series
            if self._loaded_raw_time_series is not None
            else self._loaded_time_series
        )   # (T, 200)
        T  = len(ts)
        if T < 6:
            return {"type": "error", "success": False,
                    "message": f"时序数据太短（{T} 帧），至少需要 6 帧"}

        # Default window split: caller can override
        w1s = int(request.get("window1_start", 0))
        w1e = int(request.get("window1_end",   T // 2))
        w2s = int(request.get("window2_start", T // 2))
        w2e = int(request.get("window2_end",   T))

        w1s = max(0, min(w1s, T - 1));  w1e = max(w1s + 1, min(w1e, T))
        w2s = max(0, min(w2s, T - 1));  w2e = max(w2s + 1, min(w2e, T))

        ref_ts  = ts[w1s:w1e]
        test_ts = ts[w2s:w2e]

        try:
            overlay, summary = BrainStateAnalyzer.compute_deviation_map(ref_ts, test_ts)
            summary["window1"] = f"帧 {w1s}–{w1e}"
            summary["window2"] = f"帧 {w2s}–{w2e}"
            summary["total_frames"] = T
            self.logger.info(
                f"偏差分析完成: 均值Cohen's d={summary['mean_z_score']}, "
                f"最大Cohen's d={summary['max_z_score']}, "
                f"中等效应以上区域数={summary['n_outliers_2std']}"
            )
            return {
                "type":    "brain_analysis_result",
                "method":  "deviation",
                "activity": overlay.tolist(),
                "summary": summary,
                "regions_of_interest": summary["top_regions"],
                "success": True,
            }
        except Exception as exc:
            return {"type": "error", "message": f"偏差分析失败: {exc}"}

    def _generate_demo_time_series(self, T: int = 300) -> "np.ndarray":
        """Generate synthetic 200-region time series using 7-network oscillators.

        Fully vectorized: replaces the original T×N nested Python loop with
        NumPy broadcasting over (T, 1) and (1, N) arrays, yielding the same
        numerical output at ~50× the speed (T=300, N=200 → 60 k iterations).
        """
        import numpy as np
        n = 200
        net_freqs  = np.array([0.012, 0.020, 0.035, 0.028, 0.008, 0.025, 0.010])
        net_phases = np.array([0.0,   1.0,   2.1,   0.7,   3.2,   1.8,   0.4  ])
        net_size   = n // 7
        rng        = np.random.default_rng(0)

        # Region → network assignment; capped at 6 to handle the last partial band
        i_arr   = np.arange(n)                               # (n,)
        k_arr   = np.minimum(i_arr // net_size, 6)           # (n,) network index
        t_arr   = np.arange(T)[:, None]                      # (T, 1)  time steps
        i_2d    = i_arr[None, :]                             # (1, n)  region indices
        nfreqs  = net_freqs[k_arr][None, :]                  # (1, n)  per-region frequency
        nphases = net_phases[k_arr][None, :]                 # (1, n)  per-region phase

        v = (0.36
             + 0.22 * np.sin(nfreqs * t_arr + nphases + i_2d * 0.08)
             + 0.04 * np.sin(0.003 * t_arr  + i_2d   * 0.25)
             + rng.standard_normal((T, n)) * 0.025)
        return np.clip(v, 0.0, 1.0).astype(np.float32)

    # ------------------------------------------------------------------ #
    #  Demo stimulation simulation (no trained model required)             #
    # ------------------------------------------------------------------ #

    def _demo_simulate(
        self,
        target_regions: list,
        amplitude: float,
        pattern: str,
        frequency: float,
        duration: int,
        n_regions: int = 200,
        initial_state: list = None,
    ) -> list:
        """Generate a realistic stimulation animation without a trained model.

        Returns a list of {"activity": [200 floats]} frames showing:
          1. Pre-stim baseline  (10 frames)
          2. Stimulation active (``duration`` frames, capped at 60)
          3. Post-stim recovery (10 frames)

        When ``initial_state`` is provided (the user's selected time point
        from loaded data), it is used as the starting brain state so the
        stimulation is clearly anchored to the user's actual data rather than
        a freshly generated synthetic baseline.  When omitted, the 7-network
        sinusoidal model from ``handle_get_state`` is used as a fallback.

        Spatial spread is approximated via a Gaussian kernel over the
        Fibonacci-sphere positions baked into the visualisation (same formula
        as ``makeBrainPositions`` in app.js).
        """
        import numpy as np
        import time

        # Gaussian spatial spread sigma (mm). ~30 mm ≈ typical tDCS/TMS spread
        # radius observed in neuroimaging studies; keeps neighbouring regions
        # within the same cortical network correlated.
        _SPREAD_SIGMA_MM = 30.0
        # Cap stimulation frames to keep the WebSocket payload manageable.
        _MAX_STIM_FRAMES = 60

        # Retrieve the module-level cached Fibonacci positions (computed once).
        # This replaces the former per-call _brain_positions() nested function.
        positions = _get_brain_positions(n_regions)  # (200, 3)

        # ── Pre-compute Gaussian spatial-spread weights ────────────────────
        spread_weights = np.zeros(n_regions, dtype=np.float32)
        for tid in target_regions:
            if 0 <= tid < n_regions:
                d = np.linalg.norm(positions - positions[tid], axis=1)
                spread_weights += np.exp(-(d ** 2) / (2 * _SPREAD_SIGMA_MM ** 2))
        # Homotopic (callosal) activation: stimulating one hemisphere also weakly
        # excites the contralateral homologous region via corpus callosum.
        # Region 0-99 = left hemisphere; 100-199 = right hemisphere.
        # This produces visible bilateral propagation in the demo without adding
        # a full W matrix.  Strength 0.40 matches typical callosal coupling ratios.
        _HOMO_STRENGTH = 0.40
        for tid in target_regions:
            if 0 <= tid < n_regions:
                homo_id = tid + 100 if tid < 100 else tid - 100
                if 0 <= homo_id < n_regions:
                    d = np.linalg.norm(positions - positions[homo_id], axis=1)
                    spread_weights += _HOMO_STRENGTH * np.exp(
                        -(d ** 2) / (2 * _SPREAD_SIGMA_MM ** 2)
                    )
        # Normalise: peak = amplitude at target, falls off with distance
        if spread_weights.max() > 0:
            spread_weights /= spread_weights.max()

        # ── 7-network baseline oscillation (matches app.js demoUpdate) ────
        _net_freqs  = np.array([0.012, 0.020, 0.035, 0.028, 0.008, 0.025, 0.010])
        _net_phases = np.array([0.0,   1.0,   2.1,   0.7,   3.2,   1.8,   0.4  ])
        net_size   = n_regions // 7
        t0         = time.time()

        # Pre-compute per-region network assignment for vectorized _baseline calls.
        _i_arr   = np.arange(n_regions, dtype=np.float32)
        _k_arr   = np.minimum(np.arange(n_regions) // net_size, 6)  # (n,) int
        _nfreqs  = _net_freqs[_k_arr]   # (n,) per-region oscillation frequency
        _nphases = _net_phases[_k_arr]  # (n,) per-region oscillation phase

        def _baseline(tick: float) -> np.ndarray:
            """Vectorized 7-network sinusoidal baseline — no Python loop."""
            v = (0.36
                 + 0.22 * np.sin(_nfreqs * tick + _nphases + _i_arr * 0.08)
                 + 0.04 * np.sin(0.003 * tick + _i_arr * 0.25))
            return np.clip(v, 0.0, 1.0).astype(np.float32)

        PRE  = 10
        DUR  = min(int(duration), _MAX_STIM_FRAMES)

        # ── Stimulation pattern function ───────────────────────────────────
        # NOTE: We model the *neural response envelope*, not the raw electrical
        # waveform.  At 10 fps the Nyquist limit is 5 Hz, so sampling a 10 Hz
        # sine wave at integer frame indices yields sin(2πn)=0 for every frame
        # (zero effect visible to the user).  Instead we show the slow-timescale
        # change in cortical excitability that is the brain's actual response to
        # sustained stimulation — which is the quantity of clinical interest.
        def _stim_amp(relative_t: int) -> float:
            # Center each step in its time slot so the bell envelope never evaluates
            # at exactly 0 or 1 — this prevents zero-amplitude frames for small DUR.
            # Formula: (k + 0.5) / DUR  ∈ (0, 1) exclusive, matching the NPI convention
            # of a small perturbation applied mid-interval.
            progress = (relative_t + 0.5) / max(DUR, 1)
            if pattern == "sine":
                slow_cycles = min(frequency / 10.0, 3.0)   # ≤ 3 visible cycles
                osc = 0.20 * np.sin(2 * np.pi * slow_cycles * progress)
                return amplitude * (np.sin(np.pi * progress) + osc)
            elif pattern == "pulse":
                return amplitude * np.exp(-relative_t * 0.12)
            elif pattern == "ramp":
                return amplitude * progress
            else:  # constant / unknown — smooth ramp-up to avoid sudden color jump
                return amplitude * min(1.0, relative_t / max(DUR * 0.15, 1.0))

        # Fixed seed so the noise is reproducible (same run → same animation).
        rng = np.random.default_rng(0)

        # ── Determine baseline (init_arr) for both simulation paths ──────────
        if initial_state is not None and len(initial_state) >= n_regions:
            if len(initial_state) > n_regions:
                self.logger.warning(
                    f"initial_state has {len(initial_state)} elements but n_regions={n_regions}; "
                    "truncating — check frontend/backend region count mismatch"
                )
            init_arr = np.array(initial_state[:n_regions], dtype=np.float32)
        else:
            # Fallback: use the sinusoidal 7-network baseline at PRE-1 as reference
            init_arr = _baseline(t0 * 200 + (PRE - 1) * 4)

        def _wc_step(state: np.ndarray, stim_in: np.ndarray) -> np.ndarray:
            """Deviation-based leaky integrator — physical spread, no connectivity W.

            This is the Wilson-Cowan fallback for when no trained model is
            available.  It intentionally contains NO connectivity matrix W:

            The NPI principle is to stimulate a region and *observe* which
            other regions change — that observation is how you discover
            connectivity.  If we pre-define W based on spatial proximity, we
            are deciding connectivity ourselves (circular reasoning), which
            defeats the entire purpose.

            "stim_in" is pre-scaled by ``spread_weights`` (a Gaussian kernel
            centred on the target, sigma ≈ 30 mm) before being passed here.
            This Gaussian represents the *physical extent of the stimulation
            tool* (e.g. TMS coil), NOT neural network connectivity.  Regions
            that fall within the coil's footprint receive a direct biophysical
            input; the question of which *connected* regions then respond is
            exactly what EC inference is for.  There is no W term here because
            that would be substituting an assumed spatial prior for the actual
            learned connectivity.

            Model:
              - deviation = state − init_arr  (0 when at rest)
              - delta     = tanh(stim_in * 2.0) * 0.04  (stim_in includes tool spread)
              - leak      = deviation * 0.10  (returns to init_arr in ~10 steps)

            Without stimulation: deviation stays at 0 → state stable at init_arr.
            With stimulation:    regions within the tool's physical footprint
                                 rise above init_arr; leak prevents saturation.
            """
            deviation = state - init_arr
            delta     = np.tanh(stim_in * 2.0) * 0.04
            leak      = deviation * 0.10
            noise     = rng.standard_normal(n_regions).astype(np.float32) * 0.008
            return np.clip(state + delta - leak + noise, 0.0, 1.0)

        _NO_STIM = np.zeros(n_regions, dtype=np.float32)
        POST  = 10
        frames = []

        if initial_state is not None and len(initial_state) >= n_regions:
            # 1. Pre-stim: WC evolution from initial state with no stimulation.
            # Using _wc_step (not static copies) so frames 0..PRE-1 evolve
            # naturally — the same continuous-dynamics convention used by the
            # surrogate-MLP path.  The fixed seed ensures the pre-stim noise is
            # reproducible across the stimulated and counterfactual trajectories.
            current = init_arr.copy()
            for _ in range(PRE):
                current = _wc_step(current, _NO_STIM)
                frames.append({"activity": current.tolist()})

            # 2. Stimulation active: deviation-based WC dynamics from end of
            # pre-stim phase (continuous trajectory, not restarted from init_arr).
            for k in range(DUR):
                current = _wc_step(current, _stim_amp(k) * spread_weights)
                frames.append({"activity": current.tolist()})

            # 3. Post-stim: continued dynamics with no external input.
            #    Leak pulls state back toward init_arr naturally.
            for _ in range(POST):
                current = _wc_step(current, _NO_STIM)
                frames.append({"activity": current.tolist()})

        else:
            # Fallback: no data loaded — start from sinusoidal 7-network baseline.
            # 1. Pre-stim baseline (sinusoidal)
            for k in range(PRE):
                frames.append({"activity": _baseline(t0 * 200 + k * 4).tolist()})

            # 2. Stimulation active: deviation-based WC from last pre-stim frame.
            current = np.array(frames[-1]["activity"], dtype=np.float32)
            for k in range(DUR):
                current = _wc_step(current, _stim_amp(k) * spread_weights)
                frames.append({"activity": current.tolist()})

            # 3. Post-stim: return to baseline
            for _ in range(POST):
                current = _wc_step(current, _NO_STIM)
                frames.append({"activity": current.tolist()})

        return frames

    # ------------------------------------------------------------------ #
    #  List all discoverable .pt cache files                              #
    # ------------------------------------------------------------------ #

    async def handle_list_cache_files(self, _request: Dict[str, Any]) -> Dict[str, Any]:
        """Return all .pt cache files discoverable on the server file system.

        Scans the same candidate directories used by ``_find_cache_file``
        and returns every file that passes the minimum-size filter.

        Response::

            {
              "type":  "cache_files_list",
              "files": ["path/to/hetero_graphs.pt", …]   # sorted, deduplicated
            }
        """
        seen: set = set()
        files: list = []

        for d in self._CACHE_SEARCH_DIRS:
            if not d.exists():
                continue
            # Preferred filenames first, then any .pt
            candidates = []
            for name in self._PREFERRED_CACHE_NAMES:
                candidates.extend(d.glob(f"**/{name}"))
            candidates.extend(d.glob("**/*.pt"))

            for f in candidates:
                if "__pycache__" in str(f):
                    continue
                try:
                    if f.stat().st_size <= self._MIN_CACHE_SIZE:
                        continue
                except OSError:
                    continue
                resolved = str(f.resolve())
                if resolved in seen:
                    continue
                seen.add(resolved)
                # Return path relative to cwd when possible (shorter, portable)
                try:
                    display = str(f.resolve().relative_to(Path(".").resolve()))
                except ValueError:
                    display = str(f)
                files.append(display)

        files.sort()
        self.logger.info(f"list_cache_files → {len(files)} file(s) found")
        return {"type": "cache_files_list", "files": files}

    # ------------------------------------------------------------------ #
    #  Load a .pt cache file and stream all time frames                    #
    # ------------------------------------------------------------------ #

    async def handle_load_cache(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Load a .pt cache file and return its full time series as frames.

        Accepted request fields:
          path (str, optional): path to the .pt file; if omitted, auto-detects
                                the first suitable file under the project tree.

        Companion-file auto-loading
        ---------------------------
        The upstream training system saves fMRI and EEG into **separate** files:
          - ``hetero_graphs.pt`` → Dict[task, List[HeteroData]]  (fMRI node type)
          - ``eeg_data.pt``      → Dict[task, Dict[state, HeteroData]] (EEG node type)

        When only one modality is found in the primary file we try to locate the
        companion file in the same directory so that both fMRI and EEG frames can
        be shown together in the UI.  The companion is loaded transparently; the
        user never needs to load two files manually.

        Response:
          { "type": "cache_loaded", "path": "…", "n_frames": N,
            "frames": [{"activity": [200 floats]}, …],
            "frames_fmri": [...] or null,
            "frames_eeg":  [...] or null,
            "modalities":  ["fmri"] | ["eeg"] | ["fmri","eeg"] }
        """
        import torch

        raw_path = request.get("path")
        cache_path = Path(raw_path) if raw_path else self._find_cache_file()

        if cache_path is None or not cache_path.exists():
            return {
                "type": "error",
                "message": f"找不到缓存文件: {raw_path or '(自动检测失败)'}",
            }

        try:
            data = torch.load(str(cache_path), map_location="cpu", weights_only=False)
        except Exception as exc:
            return {"type": "error", "message": f"文件加载失败: {exc}"}

        both = self._extract_time_series_both(data)
        frames_fmri = both.get("fmri", [])
        frames_eeg  = both.get("eeg", [])
        modalities  = both.get("modalities", [])

        # ── Companion-file auto-loading ────────────────────────────────────
        # If one modality is missing, look for its dedicated companion file
        # in the same directory.  This handles the common case where the
        # upstream training pipeline saved fMRI and EEG into separate files:
        #   hetero_graphs.pt  ← fMRI  (Dict[task, List[HeteroData]])
        #   eeg_data.pt       ← EEG   (Dict[task, Dict[state, HeteroData]])
        if not frames_fmri or not frames_eeg:
            companion = self._find_companion_cache(cache_path, has_fmri=bool(frames_fmri),
                                                   has_eeg=bool(frames_eeg))
            if companion is not None:
                try:
                    companion_data = torch.load(str(companion), map_location="cpu",
                                                weights_only=False)
                    comp_both = self._extract_time_series_both(companion_data)
                    if not frames_fmri and comp_both.get("fmri"):
                        frames_fmri = comp_both["fmri"]
                        both["n_fmri_regions"] = comp_both.get("n_fmri_regions", 0)
                        self.logger.info(
                            f"伴随文件加载 fMRI 数据: {companion} → {len(frames_fmri)} 帧"
                        )
                    if not frames_eeg and comp_both.get("eeg"):
                        frames_eeg = comp_both["eeg"]
                        both["n_eeg_channels"] = comp_both.get("n_eeg_channels", 0)
                        self.logger.info(
                            f"伴随文件加载 EEG 数据: {companion} → {len(frames_eeg)} 帧"
                        )
                    modalities = (["fmri"] if frames_fmri else []) + (["eeg"] if frames_eeg else [])
                except Exception as exc:
                    self.logger.warning(f"伴随文件加载失败 ({companion}): {exc}")

        # Primary frames: prefer fMRI, fall back to EEG
        primary = frames_fmri if frames_fmri else frames_eeg
        if not primary:
            return {"type": "error", "message": "无法从文件中提取脑区时间序列"}

        self.logger.info(
            f"✓ 缓存加载完成: {cache_path} → {len(primary)} 帧 "
            f"(模态: {modalities})"
        )

        # Store the primary time series for later use by validate_ec / analyze_brain
        import numpy as np
        try:
            self._loaded_time_series = np.array(
                [f["activity"] for f in primary], dtype=np.float32
            )   # (T, 200)
            self._loaded_cache_path = str(cache_path)
            # Also store raw (un-per-frame-normalised) values so that the deviation
            # analysis uses the original sensor amplitudes, not normalised [0,1] data.
            # EEG frames are per-frame min-max normalised (loses temporal structure);
            # raw values preserve the genuine between-task amplitude differences.
            if primary and "raw" in primary[0]:
                self._loaded_raw_time_series = np.array(
                    [f.get("raw", f["activity"]) for f in primary], dtype=np.float32
                )   # (T, 200)
            else:
                self._loaded_raw_time_series = None
        except Exception:
            self._loaded_raw_time_series = None

        return {
            "type":           "cache_loaded",
            "path":           str(cache_path),
            "n_frames":       len(primary),
            "frames":         primary,           # backward-compat: primary modality
            "frames_fmri":    frames_fmri or None,
            "frames_eeg":     frames_eeg  or None,
            "modalities":     modalities,
            # Actual counts before interpolation (fallback = 200 standard Schaefer parcellation)
            "n_fmri_regions": both.get("n_fmri_regions", 200),
            "n_eeg_channels": both.get("n_eeg_channels", 0),
            "success":        True,
        }

    def _find_cache_file(self) -> Optional[Path]:
        """Auto-detect the first suitable .pt cache file in common locations."""
        for d in self._CACHE_SEARCH_DIRS:
            if not d.exists():
                continue
            for name in self._PREFERRED_CACHE_NAMES:
                for f in d.glob(f"**/{name}"):
                    if f.stat().st_size > self._MIN_CACHE_SIZE:
                        return f
            for f in d.glob("**/*.pt"):
                if "__pycache__" not in str(f) and f.stat().st_size > self._MIN_CACHE_SIZE:
                    return f
        return None

    def _find_companion_cache(
        self,
        primary_path: Path,
        has_fmri: bool,
        has_eeg: bool,
    ) -> "Optional[Path]":
        """Look for the complementary modality file next to ``primary_path``.

        The upstream training pipeline writes fMRI and EEG to two separate files:
          ``hetero_graphs.pt`` — fMRI  (Dict[task, List[HeteroData]])
          ``eeg_data.pt``      — EEG   (Dict[task, Dict[state, HeteroData]])

        When the primary file contains only one modality this method returns the
        companion file path (if it exists in the same directory and is large
        enough to be a valid cache), enabling ``handle_load_cache`` to merge
        both modalities into a single response.

        Args:
            primary_path : Path of the file already loaded.
            has_fmri     : Whether the primary file already yielded fMRI frames.
            has_eeg      : Whether the primary file already yielded EEG frames.

        Returns:
            Path to the companion file, or None if not found / not needed.
        """
        if has_fmri and has_eeg:
            return None   # both modalities already present — nothing to do

        parent = primary_path.parent
        name   = primary_path.name.lower()

        # Determine which companion filenames to look for based on what's missing.
        if not has_fmri:
            # Primary has EEG (or nothing); look for the fMRI companion.
            candidates = ["hetero_graphs.pt"]
        else:
            # Primary has fMRI; look for the EEG companion.
            candidates = ["eeg_data.pt"]

        for cname in candidates:
            companion = parent / cname
            if (companion.exists()
                    and companion != primary_path
                    and companion.stat().st_size > self._MIN_CACHE_SIZE):
                self.logger.info(f"发现伴随模态文件: {companion}")
                return companion

        return None

    def _find_all_hetero_data(self, data, _depth: int = 0) -> list:
        """Recursively collect ALL HeteroData objects from a nested structure.

        When a cache file stores ``Dict[task, List[HeteroData]]`` the full
        time series is split across multiple HeteroData chunks (each holding
        ``spatial_T`` frames, e.g. 384) to keep training memory bounded.
        This method collects every chunk so the caller can concatenate them
        and recover the complete time series.

        Args:
            data:   Arbitrary nested structure (HeteroData, list, tuple, dict).
            _depth: Internal recursion depth counter.  Stops at
                    ``_MAX_HETERO_RECURSION_DEPTH`` to prevent stack overflow
                    on corrupted or unexpectedly deep structures.
        """
        if _depth > _MAX_HETERO_RECURSION_DEPTH:
            self.logger.warning(
                "_find_all_hetero_data: 递归深度超过100，停止搜索（数据结构可能损坏）"
            )
            return []
        results = []
        if hasattr(data, "node_types"):
            results.append(data)
        elif isinstance(data, (list, tuple)):
            for item in data:
                results.extend(self._find_all_hetero_data(item, _depth + 1))
        elif isinstance(data, dict):
            for v in data.values():
                results.extend(self._find_all_hetero_data(v, _depth + 1))
        return results

    def _extract_time_series(self, data) -> list:
        """Extract per-time-point activity frames from a cache .pt object.

        Strategy (in order of preference):
          1. ``fmri.x_seq`` (shape N×T×F, N == 200 ROIs) → direct 1-to-1 mapping.
          2. ``eeg.x_seq``  (shape N_eeg×T×F, N_eeg ≠ 200) → linear interpolation
             to 200 visualisation slots using np.interp.

        All activity values are normalised to [0, 1] via global 5th/95th
        percentile clipping (robust to outliers in both modalities).
        """
        both = self._extract_time_series_both(data)
        primary = both.get("fmri") or both.get("eeg") or []
        return primary

    def _extract_time_series_both(self, data) -> dict:
        """Extract fMRI and EEG frame sequences from a cache .pt object.

        Returns a dict with keys:
          fmri       – list of {"activity": [200 floats]} or [] if unavailable
          eeg        – list of {"activity": [200 floats]} or [] if unavailable
          modalities – list of available modality names, e.g. ["fmri","eeg"]

        Normalisation strategy:
          fMRI: global 5th/95th-percentile across all time + channels → preserves
                absolute activity level relationships between frames.
          EEG:  per-frame min-max → shows relative spatial variation at each
                instant (EEG temporal variance dominates spatial variance, so
                global normalisation makes all channels appear the same colour).

        Full-series reconstruction:
          Training stores data as Dict[task, List[HeteroData]] where each
          HeteroData holds exactly spatial_T (e.g. 384) consecutive frames to
          keep GPU memory bounded.  This method collects ALL HeteroData chunks
          and concatenates their x_seq tensors along the time axis (dim=1) so
          that the visualiser sees the complete, un-truncated recording.
        """
        import torch
        import numpy as np

        graphs = self._find_all_hetero_data(data)
        if not graphs:
            return {"fmri": [], "eeg": [], "modalities": []}

        n_regions = 200

        def _frames_from_xseq(x_seq, n_out: int) -> list:
            """Global percentile normalisation for fMRI.

            Each frame contains:
              activity – [0,1] normalised values (drives sphere colour)
              raw      – original sensor values (shown in hover tooltip)

            Fully vectorized for the common N==n_out fMRI case: the entire
            (N, T) normalisation is computed as a single NumPy operation
            rather than one per-frame Python call.  The interpolation path
            (N != n_out, rare) retains a T-iteration loop because np.interp
            is 1-D only, but normalisation is still batched.
            """
            x = x_seq.cpu().float()
            if x.ndim == 2:
                x = x.unsqueeze(-1)      # (N, T) → (N, T, 1)
            N, T, _ = x.shape
            x_np  = x[:, :, 0].numpy()   # (N, T) float32
            flat  = x_np.ravel()
            p5, p95 = np.percentile(flat, 5), np.percentile(flat, 95)
            scale   = max(p95 - p5, 1e-6)

            if N == n_out:
                # Batch normalise the entire (N, T) tensor at once — no per-frame loop
                norms = np.clip((x_np - p5) / scale, 0.0, 1.0).astype(np.float32)
                return [
                    {"activity": norms[:, t].tolist(),
                     "raw":      x_np[:, t].astype(np.float32).tolist()}
                    for t in range(T)
                ]

            # Interpolation path (e.g. fMRI with non-standard parcellation)
            src_idx = np.linspace(0.0, 1.0, N)
            dst_idx = np.linspace(0.0, 1.0, n_out)
            norms   = np.clip((x_np - p5) / scale, 0.0, 1.0)   # (N, T) batch
            result  = []
            for t in range(T):
                arr = np.interp(dst_idx, src_idx, norms[:, t]).astype(np.float32)
                raw = np.interp(dst_idx, src_idx, x_np[:, t]).astype(np.float32)
                result.append({"activity": arr.tolist(), "raw": raw.tolist()})
            return result

        def _frames_from_xseq_eeg(x_seq, n_out: int) -> list:
            """Per-frame min-max normalisation for EEG.

            EEG temporal variance >> spatial variance, so global normalisation
            collapses all channels to the same colour at any given instant.
            Per-frame normalisation exposes the relative spatial distribution.

            Each frame contains:
              activity – [0,1] normalised values (drives sphere colour)
              raw      – original sensor values (shown in hover tooltip)

            Vectorized for N==n_out: per-frame min/max are computed as
            column-wise reductions on the full (N, T) matrix so that a single
            clip call produces all normalised values at once.
            """
            x = x_seq.cpu().float()
            if x.ndim == 2:
                x = x.unsqueeze(-1)      # (N, T) → (N, T, 1)
            N, T, _ = x.shape
            x_np = x[:, :, 0].numpy()   # (N, T)

            if N == n_out:
                # Vectorized per-frame min-max: shape (1, T) broadcasts over (N, T)
                sig_min = x_np.min(axis=0, keepdims=True)   # (1, T)
                sig_max = x_np.max(axis=0, keepdims=True)   # (1, T)
                scale   = np.maximum(sig_max - sig_min, 1e-6)
                norms   = np.clip((x_np - sig_min) / scale, 0.0, 1.0).astype(np.float32)
                return [
                    {"activity": norms[:, t].tolist(),
                     "raw":      x_np[:, t].astype(np.float32).tolist()}
                    for t in range(T)
                ]

            # Interpolation path (EEG with N_eeg channels → n_out visualisation slots)
            src_idx = np.linspace(0.0, 1.0, N)
            dst_idx = np.linspace(0.0, 1.0, n_out)
            result  = []
            for t in range(T):
                sig = x_np[:, t]
                sig_min, sig_max = float(sig.min()), float(sig.max())
                scale = max(sig_max - sig_min, 1e-6)
                norm  = np.clip((sig - sig_min) / scale, 0.0, 1.0)
                arr   = np.interp(dst_idx, src_idx, norm).astype(np.float32)
                raw   = np.interp(dst_idx, src_idx, sig).astype(np.float32)
                result.append({"activity": arr.tolist(), "raw": raw.tolist()})
            return result

        frames_fmri: list = []
        frames_eeg:  list = []
        n_fmri_raw: int   = 0   # actual number of fMRI ROIs before any interpolation
        n_eeg_raw:  int   = 0   # actual number of EEG channels before interpolation

        try:
            # Collect and concatenate x_seq tensors across all HeteroData chunks.
            # Each chunk covers spatial_T (e.g. 384) consecutive time points; the
            # full recording is recovered by concatenating along dim=1 (time axis).
            fmri_chunks: list = []
            eeg_chunks:  list = []

            for g in graphs:
                if "fmri" in g.node_types:
                    xseq = getattr(g["fmri"], "x_seq", None)
                    if xseq is None:
                        # Fallback: some older training configurations store the
                        # fMRI time series in the standard `.x` attribute rather
                        # than the custom `.x_seq` field.  Mirror the same
                        # fallback that already exists for the EEG path.
                        xseq = getattr(g["fmri"], "x", None)
                    if xseq is not None:
                        if xseq.ndim == 2:
                            xseq = xseq.unsqueeze(-1)
                        fmri_chunks.append(xseq)
                        if n_fmri_raw == 0:
                            n_fmri_raw = int(xseq.shape[0])

                if "eeg" in g.node_types:
                    xseq = getattr(g["eeg"], "x_seq", None)
                    if xseq is None:
                        xseq = getattr(g["eeg"], "x", None)
                    if xseq is not None:
                        if xseq.ndim == 2:
                            xseq = xseq.unsqueeze(-1)
                        eeg_chunks.append(xseq)
                        if n_eeg_raw == 0:
                            n_eeg_raw = int(xseq.shape[0])

            if fmri_chunks:
                fmri_cat = torch.cat(fmri_chunks, dim=1)  # (N, T_total, F)
                frames_fmri = _frames_from_xseq(fmri_cat, n_regions)

            if eeg_chunks:
                eeg_cat = torch.cat(eeg_chunks, dim=1)    # (N_eeg, T_total, F)
                frames_eeg = _frames_from_xseq_eeg(eeg_cat, n_regions)

            if len(graphs) > 1:
                self.logger.info(
                    f"_extract_time_series_both: 合并 {len(graphs)} 个数据块 → "
                    f"fMRI {len(frames_fmri)} 帧, EEG {len(frames_eeg)} 帧"
                )

        except Exception as exc:
            self.logger.error(f"_extract_time_series_both error: {exc}")

        modalities = (["fmri"] if frames_fmri else []) + (["eeg"] if frames_eeg else [])
        return {
            "fmri":           frames_fmri,
            "eeg":            frames_eeg,
            "modalities":     modalities,
            "n_fmri_regions": n_fmri_raw,   # e.g. 200 (direct mapping)
            "n_eeg_channels": n_eeg_raw,    # e.g. 64 or 128 (interpolated to 200)
        }

    def _extract_activity_array(self, result: Dict) -> list:
        """Extract a flat [0,1] activity list from various result-dict formats.

        Handles both:
          A) model_server._state_to_json():
             {"regions": [{"activity": float, …}, …], …}
          B) BrainStateExporter.export_brain_state():
             {"brain_state": {"regions": [{"activity": {"fmri": {"amplitude": float}}}}]}}
        """
        # Format A: model_server output
        if "regions" in result:
            return [float(r.get("activity", 0.5)) for r in result["regions"]]

        # Format B: exporter output
        if "brain_state" in result:
            out = []
            for r in result["brain_state"].get("regions", []):
                act = r.get("activity", {})
                if isinstance(act, dict):
                    fmri = act.get("fmri", {})
                    out.append(float(fmri.get("amplitude", 0.5))
                               if isinstance(fmri, dict) else 0.5)
                else:
                    out.append(float(act))
            return out

        return []

    async def start_async(self):
        """Start server asynchronously (preferred entry point)."""
        if not WEBSOCKETS_AVAILABLE:
            raise ImportError("websockets package is required")
        self.logger.info(f"Starting WebSocket server on {self.host}:{self.port}")
        async with websockets.serve(self.handle_client, self.host, self.port):
            self.logger.info("Server started successfully")
            await asyncio.Future()  # Run forever
